manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: Neargye 
      url-base: https://github.com/Neargye
    - name: TartanLlama 
      url-base: https://github.com/TartanLlama
    - name: embedded-template-library 
      url-base: https://github.com/ETLCPP
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.6.0
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_nordic # required for Nordic
          - littlefs   # required for file system
    - name: magic_enum
      remote: Neargye
      revision: v0.9.5
    - name: expected
      remote: TartanLlama
      revision: v1.1.0
    - name: optional
      remote: TartanLlama
      revision: v1.1.0
    - name: etl
      remote: embedded-template-library 
      revision: 20.38.10
  self:
    path: notus