CONFIG_DEBUG=y

CONFIG_LOG=y

CONFIG_MAIN_STACK_SIZE=4096

CONFIG_APPLICATION_LOG_LEVEL_INF=y
CONFIG_MODULE1_LOG_LEVEL_INF=y

CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_OBSERVER_NAME=y
CONFIG_ZBUS_RUNTIME_OBSERVERS=y