name: Delete Old Docker
on: [delete]
jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
    - name: Remove Docker Tag
      uses: ArchieAtkinson/remove-dockertag-action@v0.0
      with:
        tag_name: ${{ github.event.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}